### ISSUE TITLE
Design der karten

### ISSUE THREAD

**Issue by grosim6** [TheRealAjay/solitaireonline-backend#5]
User soll das spiel personalisieren können

**Comment by theonearon** [comment]
na

**Comment by 6lyxt** [comment]
+1

**Comment by theonearon** [comment]
-1

**Comment by theonearon** [comment]
@6lyxt ich weiß wo du hacklst, I kumm glei vorbei wennst ned aufhörst meine wunderschöne Projekte zu verarschen

**Comment by 6lyxt** [comment]
@TheRealAjay i werd auf ein bestimmtes kissen in deinem bett ejakulieren

**Comment by 6lyxt** [comment]
owo

**Comment by theonearon** [comment]
@6lyxt ok
